org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
mod_version=1.3.0-port2-atm11-0.9.0
jei_version=29.37.0.99
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109
java_version=25
mod_id=mbtool
mod_name=MultiBuilder
mod_license=MIT
